#pragma kernel CSMain
#pragma kernel updateCopyBlack


RWTexture2D<float2> UVMap;

RWTexture2D<float2> copyBlackRenderTexture;
// Structure of rewardBuffer:
// rewardBuffer[0] = the current reward value
// rewardBuffer[1] = whether the pattern has been fully traced out and the task is 1, either 0 or 1
// rewardBuffer[2] = the number of pattern coordinates remaining
// rewardBuffer[3] = the index of the next closest pattern vertex

RWStructuredBuffer<int> rewardBuffer;
StructuredBuffer<float3> Positions;

uint tot_vertCount;
float maxDistance;
float3 playerPosition;
int xDimensions;



[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    uint xIndex = id.x;
    uint yIndex = id.y;
    uint index = (2 * xDimensions - 1) * yIndex + xIndex;
    float blend;

    if (index >= tot_vertCount) return;

    float3 position = Positions[index];
    float xDist = playerPosition.x - position.x;
    float zDist = playerPosition.z - position.z;
    float dist = sqrt(xDist * xDist + zDist * zDist);    
    
    int vertexIndex = rewardBuffer[3];

    if (dist <= maxDistance)
    {
        if (UVMap[int2(xIndex, yIndex)].x == 0.0f && index == (uint)vertexIndex)
        {
            InterlockedAdd(rewardBuffer[0], 2);
        }
        blend = 1.0f;
        
    }
    else
    {
        blend = 0.0f;
    }

    UVMap[int2(xIndex, yIndex)] = float2(max(UVMap[int2(xIndex, yIndex)].x, blend), 0.0f);
    
}




[numthreads(8,8,1)]
void updateCopyBlack (uint3 id : SV_DispatchThreadID)
{
    int2 coord = int2(id.xy);
    
    if (UVMap[coord].x != 0)
    {
        if (copyBlackRenderTexture[coord].x != 0.5f)
        {
            if (abs(copyBlackRenderTexture[coord].x) < 0.001f)
            {
                InterlockedAdd(rewardBuffer[0], -5);
            }
        }
            
        copyBlackRenderTexture[coord] = float2(0.5f, 0.0);
    }
    
    if (id.x == 0 && id.y == 0 && id.z == 0)
    {
        int ones = 0;
        bool done = true;
        float minDist = -1.0f;
        int minIndex;
        
        for (int i = 0; i < 28; i++)
        {
            for (int j = 0; j < 60; j++)
            {
                if (abs(copyBlackRenderTexture[int2(j, i)].x - 1.0f) < 0.001f)
                {
                    done = false;
                    ones++;

                    int index = (2 * xDimensions - 1) * i + j;
                    float3 position = Positions[index];
                    float xDist = playerPosition.x - position.x;
                    float zDist = playerPosition.z - position.z;
                    float dist = sqrt(xDist * xDist + zDist * zDist);

                    if (minDist == -1.0f)
                    {
                        minDist = dist;
                        minIndex = index;
                    }
                    else
                    {
                        if (dist < minDist)
                        {
                            minDist = dist;
                            minIndex = index;
                        }
                            
                    }
                }
            }
        }
        
        if (done == true)
        {
            rewardBuffer[1] = 1;
        }

        rewardBuffer[2] = ones;
        rewardBuffer[3] = minIndex;

    }
        
}
